version: "3.7"
services: 
    app:
        build: ./etc/phpfpm
        volumes:
            - ./src:/var/www/html
        networks:
            - magento-network
    router:
        image: nginx:1.18-alpine
        depends_on:
            - "app"
        ports:
            - "80:80"
        volumes:
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
        networks:
            - magento-network

networks:
    magento-network:
        driver: bridge